name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          version: 11.11.0
          run_install: false

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - uses: nrwl/nx-set-shas@v5

      - run: pnpm exec nx affected -t lint test build typecheck

      - run: pnpm exec nx fix-ci
        if: always()
